AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Lambda function with structured logging using Go's log/slog

Resources:
  LambdaSlogLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/lambda-slog-LambdaSlogFunction
      RetentionInDays: 7

  LambdaSlogFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      BuildProperties:
        BuildTarget: bootstrap
    Properties:
      CodeUri: .
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - arm64
      Environment:
        Variables:
          LOG_LEVEL: INFO
          SERVICE_NAME: lambda-slog
